package com.boom.pedagogy.domain;

public enum ReviewReason {
    LOW_ACCURACY,
    ACTIVE_GAP,
    FAILED_MASTERY_CHECK,
    OVERDUE_REVIEW,
    CRITICAL_OVERDUE,
    MODERATE_INACTIVITY,
    ABANDONMENT,
    LONG_ABSENCE,
    PREREQUISITE_WEAKNESS,
    CORRELATED_TOPIC_REMEDIATION
}
